### ISSUE TITLE
Remove Q dependency

### ISSUE THREAD

**Issue by Maluen** [iorad/knowledgebase#3]
Please read https://github.com/iorad/knowledgebase/commit/2961a0b840f50b7375a373eaf440ba1de4fb7466#commitcomment-10416135

> $.ajax supports then() by default:
> 
> http://api.jquery.com/jquery.ajax/
> 
> Is it possible to remove the Q dependency or have it more promise-library agnostic? For example in our system we are using RSVP and would be quite bad to have to include another promise library just to make it work.

**Comment by iorad** [comment]
@dan753722 is the above possible?

**Comment by dan753722** [comment]
@Maluen certainly. I can do that.

**Comment by Maluen** [comment]
Thanks!
